---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unitycatalog
  namespace: $(namespace)
  labels:
    app: unitycatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unitycatalog
  template:
    metadata:
      labels:
        app: unitycatalog
    spec:
      securityContext:
        runAsUser: 185
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: unitycatalog
        image: quay.io/tcarland/unitycatalog:0.2.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        env: []
        ports:
        - containerPort: 8080
          name: ucone
        - containerPort: 8081
          name: uctwo
        volumeMounts:
        - name: hibernate-cfg-vol
          mountPath: /opt/unitycatalog/etc/conf/hibernate.properties
          subPath: hibernate.properties
        - name: hibernate-cfg-vol
          mountPath: /opt/unitycatalog/etc/conf/server.properties
          subPath: server.properties
        command: [ "/opt/entrypoint.sh" ]
        resources:
          requests:
            memory: "2G"
            cpu: "1"
          limits:
            memory: "8G"
            cpu: "2"
      volumes:
        - name: hibernate-cfg-vol
          configMap:
            name: unity-configs
