apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- unity-configmap.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: unity-parameters
  envs: 
  - params.env

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: unity-secrets
  envs: 
  - secrets.env

labels:
- includeSelectors: true
  pairs:
    kustomize.component: unitycatalog