---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- unity-configmap.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: unity-parameters
  envs: 
  - params.env

generatorOptions:
  disableNameSuffixHash: true

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: unitycatalog
    app.kubernetes.io/name: unitycatalog
    app.kubernetes.io/version: 0.2.0-SNAPSHOT