---
apiVersion: v1
kind: Service
metadata:
  name: uc
  namespace: $(namespace)
spec:
  selector:
    app: unitycatalog
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: rest
      protocol: TCP
      port: 8081
      targetPort: 8081