---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unity

resources:
  - ../../base

patches:
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: unitycatalog
    spec:
      loadBalancerIP: 172.17.0.213
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: unitycatalog
      namespace: $(namespace)
    spec:
      template:
        spec:
          containers:
          - name: unitycatalog
            image: ghcr.io/tcarland/unity-k8s:v24.09.26
